name = "strava-heatmap-proxy"
type = "webpack"

account_id = ""
workers_dev = true
route = ""
zone_id = ""

# Controls how long Cloudflare should cache each tile before requesting again
# from Strava.
#
# Use "0" to disable caching.
vars = { TILE_CACHE_SECS = "86400" }
