name = "strava-heatmap-proxy"
type = "webpack"

# Change this to your own account ID
account_id = "f76e20394730f34d441eb02c46370a14"

workers_dev = true
route = ""
zone_id = ""

# Controls how long Cloudflare should cache each tile before requesting again
# from Strava.
#
# Use "0" to disable caching.
vars = { TILE_CACHE_SECS = "86400", STRAVA_ID = 0, STRAVA_COOKIES="" }
